name: Laravel

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

env:
  MYSQL_DATABASE: test_database
  DB_USER: root
  DB_PASSWORD: root

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Generate app key
        id: generate_key
        run: |
          app_key=$(php artisan key:generate --show)
          echo "APP_KEY=${app_key}" >> $GITHUB_ENV

      - name: Directory Permissions
        run: chmod -R 777 bootstrap/cache

      - name: Configure .env.testing
        run: |
          echo "DB_CONNECTION=mysql" >> .env.testing
          echo "DB_HOST=localhost" >> .env.testing
          echo "DB_PORT=3306" >> .env.testing
          echo "DB_DATABASE=test_database" >> .env.testing
          echo "DB_USERNAME=root" >> .env.testing
          echo "DB_PASSWORD=${{ env.DB_PASSWORD }}" >> .env.testing

      - name: Initialize MySQL
        run: sudo systemctl start mysql.service

      - name: Initialize database
        run: |
          mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' \
          -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
